Tpeet/add-blog-posts
eol-uchile/portal-eol pull request #73
Opened 2024-09-16 05:38 UTC by tomaspemora

update author handling, improve CSS, and add new educational content

2024-09-23 18:21 UTC, fsologureng requested changes
Creo que se puede mejorar un poco la presentación, pero sobretodo me preocupa que hay cambios que afectan a todo el sitio y no queda claro si están bien revisados en su efecto en post previos.
Además, veo que hay varios estilos en duro que podrían afectar la visualización en algunos dispositivos; En esos casos creo que es mejor dejar que funcione el estilo del sitio.

2024-09-23 18:21 UTC, fsologureng commented on public/posts/2024_09_10_inteligencia_artificial_en_di/post_es.html
> +        <ol>
No sería más apropiado usar directo una description list?
```
<dl>
     <dt>Los asistentes virtuales:</dt>
     <dd>Son herramientas poderosas que facilitan la interacción humana con la tecnología, mejorando la eficiencia y la accesibilidad en diversas tareas cotidianas (Dexs, 2023).</dd>
```

Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

2024-09-23 18:21 UTC, fsologureng commented on public/posts/2024_09_10_inteligencia_artificial_en_di/img/ia_en_di.jpg
Reducir tamaño por favor

2024-09-23 18:21 UTC, fsologureng commented on src/Content/Blog/ArticleComponent.js
> +                                                {/* <div class="row mt-4 align-items-center">
Comentario innecesario. Creo que se debe sacar.

2024-09-23 18:21 UTC, fsologureng commented on src/Content/Blog/ArticleComponent.js
> +                            {/* {
Comentario innecesario.

2024-09-23 18:21 UTC, fsologureng commented on src/Content/Blog/articles.css
Algunos de estos cambios afectan a todo el sitio? se revisó que no estropeara otros posts previos?

2024-09-23 18:21 UTC, fsologureng commented on src/index.css
Acá tb hay un cambio que afecta a todo el sitio...

2024-09-23 18:21 UTC, fsologureng commented on src/Content/Blog/ArticleComponent.js
> +    const author = article.author;
constante no se usa

2024-09-23 18:21 UTC, fsologureng commented on src/Content/Blog/ArticleComponent.js
> +                                                    {typeof article.author === 'string'
en este punto ya sabemos que `typeof article.author != 'string'` por estamos en el else de ese test.

2024-09-23 18:21 UTC, fsologureng commented on public/posts/2024_09_10_inteligencia_artificial_en_di/post_es.html
> +    <div class="row" style="font-size: 20px; line-height: 1.5;">
Este tipo de estilos en duro deberían generar diferencias con el resto del sitio...

2024-09-23 19:00 UTC, fsologureng commented
Hay un link roto en el post de Ecarinne 
![Captura de pantalla de post donde se muestra ausencia de imagen en medio del post](https://github.com/user-attachments/assets/74cf10bf-6252-4709-ad02-4a6624013d39)

2024-09-23 19:10 UTC, fsologureng commented
En el sitio de producción no se ve pegado el `autor:Oficina` 
![Detalle del autor del post Aula invertida](https://github.com/user-attachments/assets/03ba830c-1762-495f-b8f0-8bd65ec46a34)

2024-09-23 19:54 UTC, tomaspemora commented on src/Content/Blog/articles.css
- El cambio del z-index: 2 es necesario porque hay un elemento gráfico que imposibilita la selección de texto e interacción con anchors. 
![image](https://github.com/user-attachments/assets/c832b0dd-689a-4d0f-ad2e-39394724ff2d)

- En cuanto a word-wrap: break-word y word-break: break-word, los agregué porque habían títulos con palabras muy largas que no cabían en una pantalla de celular.
![image](https://github.com/user-attachments/assets/0e96a74c-3781-49dd-ad6d-88371f42a642)

- El resto de reglas, las voy a revisar más en detalle, primero por tu sugerencia de usar description lists de tal forma que ya no necesitaría las table y segundo porque puede ser que el cambio que introduje con la clase team-member genere problemas en otros lados.

2024-09-24 14:01 UTC, fsologureng commented on src/Content/Blog/articles.css
> * El cambio del z-index: 2 es necesario porque hay un elemento gráfico que imposibilita la selección de texto e interacción con anchors.

Si entiendo bien, hay una imagen que se está posicionando sobre el texto. No sería más adecuado que la imagen se pose bajo el texto (es decir cambiar el z-index de la imagen y no el del texto). No siempre es conmutativo el cambio y la imagen es decorativa, el texto no.

>     * En cuanto a word-wrap: break-word y word-break: break-word, los agregué porque habían títulos con palabras muy largas que no cabían en una pantalla de celular.

Ah perfect. Eso es muy razonable.
 
>     * El resto de reglas, las voy a revisar más en detalle, primero por tu sugerencia de usar description lists de tal forma que ya no necesitaría las table y segundo porque puede ser que el cambio que introduje con la clase team-member genere problemas en otros lados.

Las tablas son un problema en los mobiles porque no hacen wrap. Una opción es usar un plugin para tablas responsive, pero en la práctica se implementan como listas de celdas, así es que si las puedes cambiar a listas, la haces de una.

2024-11-04 14:11 UTC, fsologureng commented
> Hay un link roto en el post de Ecarinne

corregido

2024-11-04 14:12 UTC, fsologureng commented
> En el sitio de producción no se ve pegado el `autor:Oficina` 

corregido

2024-11-04 14:12 UTC, fsologureng approved these changes

2024-11-04 14:42 UTC, tomaspemora commented
oka, démosle con el merge

2024-11-04 14:52 UTC, merged